#! /bin/bash

#. /imde/switch/switchde
umask 000

#User right checking part... Nothing changes here
echo "Bitte geben Sie einen Kommentar ein: \c"
read Kommentar

#
git add .
RET_CODE=$?
if test $RET_CODE -ne 0
then
    echo "Fehler=$RET_CODE bei git add"
fi

#
set -a updatedFiles $(< git diff --name-only --staged)
RET_CODE=$?
if test $RET_CODE -ne 0
then
    echo "Fehler=$RET_CODE bei git diff"
fi

#
git commit -m "$Kommentar"
RET_CODE=$?
if test $RET_CODE -ne 0
then
    echo "Fehler=$RET_CODE bei git commit"
fi

#
git push
RET_CODE=$?
if test $RET_CODE -ne 0
then
    echo "Fehler=$RET_CODE bei git push"
fi

#
DATEINAME=`basename $1`
COMMENT=`echo $Kommentar |sed s/\ /~/g`
cp $1 ~/git/bash-tutorial/imde-dev-gitci-script/imde/data/dfue/ifs_git_install/"${LOGNAME}"@"${COMMENT}"@"$DATEINAME"
